### ISSUE TITLE
[REQ] Apply script only to certain industries

### ISSUE THREAD

**Issue by claudejdev** [MrWolfZ/transport-fever-2-more-industry-levels#1]
Hi MrWolfZ,

I'm relaying here, since I'm interested by his suggestion too, a request posted in TF.net forum :
https://www.transportfever.net/index.php?thread/14384-script-nur-auf-bestimmte-industrien-anwenden/

> (...)Now I want to apply this mod only to the processing industries, but not to the resource-producing basic industries (farm, mines, forest, oil field, ...). Can anyone help me how I can achieve this?(...)

Cheers

**Comment by MrWolfZ** [comment]
Hi. I did a quick check of the game's code and I'm afraid this is not possible, since at the time where I make the change to the number of levels it is not possible to find out whether an industry is a source or an intermediary.

There are however other mods that may make this possible. For example the "Production X4" mod does not change the number of levels but just increases the production per level. That mod already checks if an industry is a source or intermediary and adjust the production for sources differently.

**Comment by claudejdev** [comment]
Hi, thanks a lot for your answer.
